MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: vgg16.dilated_conv5_body
  METHOD: oicr_fiwsod
NUM_GPUS: 2
VGG:
  IMAGENET_PRETRAINED_WEIGHTS: 'data/pretrained_model/vgg16_caffe.pth'
SOLVER:
  WEIGHT_DECAY: 0.0005
  LR_POLICY: steps_with_decay
  BASE_LR: 0.001
  GAMMA: 0.1
  # 1x schedule (note TRAIN.IMS_PER_BATCH: 1)
  MAX_ITER: 80000
  STEPS: [0, 60000]
FAST_RCNN:
  ROI_BOX_HEAD: vgg16.roi_2mlp_head
  ROI_XFORM_METHOD: RoIPoolF
  ROI_XFORM_RESOLUTION: 7
  MLP_HEAD_DIM: 4096
TRAIN:
  SCALES: (480, 576, 688, 864, 1200)
  MAX_SIZE: 2000
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 4096
  PROPOSAL_FILES: ('data/selective_search_data/voc_2007_trainval.pkl',)
  BG_THRESH: 0.1
  SNAPSHOT_ITERS: 100000
TEST:
  SCALE: 480
  MAX_SIZE: 2000
  NMS: 0.3
  PROPOSAL_FILES: ('data/selective_search_data',)
  BBOX_AUG:
    ENABLED: True
    H_FLIP: True
    SCALES: (576, 688, 864, 1200)
    SCALE_H_FLIP: True
    SCORE_HEUR: 'AVG'
    COORD_HEUR: 'AVG'
OICR:
  Need_Reg: True
  Use_Reg_Lastbranch: True
  Test_Need_Regcls: True
  Bg2_Loss_Type: 'binary_cross_entropy'
  Bg2_Loss_Weight: 3.0
  Bg2_Loss_Weight_Chg: 1.0
  Bg2_Loss_Weight_ChgIter: 0.7
  Bg2_SelGT_Ori_Type: 'fg_oicr'
  Bg2_SelGT_Type: 'oicr_fg'
  Bg2_StartIter: 0.30
  Bg2_SelGT_Ratio: 0.14
  Bg2_SelGT_Iou: True
  Bg2_SelGT_Multi: True
  Bg2_Loss_Multi: True
  Bg2_Test: True
  Bg2_Test_MIL: True
  Bg2_Test_Type_BgWeight: 1.0
# RNG_SEED: 9
DATA_DIR: "data/"
OUTPUT_DIR: "output/fiwsod/"
